version: "3"
services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - postgres-data:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com # environment variables required
      PGADMIN_DEFAULT_PASSWORD: docker
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-db

  weather:
    build: ./load_weather
    volumes:
      - ./weather-postgres/csv:/app/csv
    depends_on:
      - postgres-db

volumes:
  postgres-data:
  pgadmin-data:
## sudo apt  install docker-compose
## docker-compose up -d
## docker-compose down
